#ifndef __DATATYPE_H__
#define __DATATYPE_H__

typedef char sql_bool;
typedef unsigned long long sql_ulonglong;
typedef unsigned long sql_ulong;
typedef char * sql_str;
typedef unsigned int sql_size;
typedef unsigned int sql_uint;


enum sqlcon_option 
{
  SQLCON_OPT_CONNECT_TIMEOUT,
  SQLCON_OPT_COMPRESS,
  SQLCON_OPT_NAMED_PIPE,
  SQLCON_INIT_COMMAND,
  SQLCON_READ_DEFAULT_FILE,
  SQLCON_READ_DEFAULT_GROUP,
  SQLCON_SET_CHARSET_DIR,
  SQLCON_SET_CHARSET_NAME,
  SQLCON_OPT_LOCAL_INFILE,
  SQLCON_OPT_PROTOCOL,
  SQLCON_SHARED_MEMORY_BASE_NAME,
  SQLCON_OPT_READ_TIMEOUT,
  SQLCON_OPT_WRITE_TIMEOUT,
  SQLCON_OPT_USE_RESULT,
  SQLCON_OPT_USE_REMOTE_CONNECTION,
  SQLCON_OPT_USE_EMBEDDED_CONNECTION,
  SQLCON_OPT_GUESS_CONNECTION,
  SQLCON_SET_CLIENT_IP,
  SQLCON_SECURE_AUTH,
  SQLCON_REPORT_DATA_TRUNCATION,
  SQLCON_OPT_RECONNECT,
  SQLCON_OPT_SSL_VERIFY_SERVER_CERT
};

enum sqlcon_status 
{
  SQLCON_STATUS_READY,
  SQLCON_STATUS_GET_RESULT,
  SQLCON_STATUS_USE_RESULT
};

enum sqlcon_protocol_type 
{
  SQLCON_PROTOCOL_DEFAULT,
  SQLCON_PROTOCOL_TCP,
  SQLCON_PROTOCOL_SOCKET,
  SQLCON_PROTOCOL_PIPE,
  SQLCON_PROTOCOL_MEMORY
};


#endif //__DATATYPE_H__